# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1/convert_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BtnBrows = QtWidgets.QPushButton(Dialog)
        self.BtnBrows.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.BtnBrows.setObjectName("BtnBrows")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(20, 100, 1000, 28)
        self.label.setObjectName('label')
        self.Convertation = QtWidgets.QPushButton(Dialog)
        self.Convertation.setGeometry(QtCore.QRect(120, 240, 151, 28))
        self.Convertation.setObjectName("Convertation")
        self.out_file = QtWidgets.QLineEdit(Dialog)
        self.out_file.setGeometry(QtCore.QRect(20, 70, 113, 22))
        self.out_file.setObjectName("out_file")
        self.label_out_file = QtWidgets.QLabel(Dialog)
        self.label_out_file.setGeometry(140, 68, 200, 28)
        self.label_out_file.setFont(QtGui.QFont('SansSerif', 10))
        self.label_out_file.setObjectName('label_out_file')
        self.label_message = QtWidgets.QLabel(Dialog)
        self.label_message.setGeometry(20, 140, 1000, 28)
        self.label_message.setObjectName('label_message')
        self.label_message.setFont(font)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Конвертор"))
        self.BtnBrows.setText(_translate("Dialog", "Открыть файл"))
        self.Convertation.setText(_translate("Dialog", "Конвертация"))
        self.label.setText(_translate('Dialog', ' '))
        self.label_out_file.setText(_translate('Dialog', '<- название файла '))
        self.label_message.setText(_translate('Dialog', ' '))

